# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/attenddb

# DB Username
spring.datasource.username=${DB_USERNAME}

# DB Password
spring.datasource.password=${DB_PASSWORD}

# SQL Init
spring.sql.init.mode=always

# Logging
logging.level.com.example.webapp.repository=DEBUG

# Active Profile
spring.profiles.active=dev

# Attendance setting
attendance.late-time=09:00
