-- Organization, administrator accounts, and one-time credential tokens.
-- Partial unique indexes and FK lookup indexes are added in V007.

CREATE TABLE public.department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_department_name
        CHECK (char_length(btrim(name)) > 0)
);

CREATE UNIQUE INDEX uq_department_name_ci
    ON public.department (lower(btrim(name)));


-- Account status is a database-level state machine. A pending invitation has
-- no password; an active account must have both a hash and a change timestamp;
-- a disabled account may represent either stage.
CREATE TABLE public.account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password_hash TEXT,
    system_role TEXT,
    status TEXT NOT NULL DEFAULT 'PENDING_SETUP',
    password_changed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_account_username
        CHECK (char_length(btrim(username)) > 0),
    CONSTRAINT ck_account_password_hash
        CHECK (password_hash IS NULL OR char_length(password_hash) > 0),
    CONSTRAINT ck_account_system_role
        CHECK (system_role IS NULL OR system_role = 'SYSTEM_ADMIN'),
    CONSTRAINT ck_account_setup_state
        CHECK (
            (status = 'PENDING_SETUP'
                AND password_hash IS NULL
                AND password_changed_at IS NULL)
            OR
            (status = 'ACTIVE'
                AND password_hash IS NOT NULL
                AND password_changed_at IS NOT NULL)
            OR
            (status = 'DISABLED'
                AND (
                    (password_hash IS NULL AND password_changed_at IS NULL)
                    OR
                    (password_hash IS NOT NULL AND password_changed_at IS NOT NULL)
                ))
        ),
    CONSTRAINT ck_account_status
        CHECK (status IN ('PENDING_SETUP', 'ACTIVE', 'DISABLED'))
);

CREATE UNIQUE INDEX uq_account_username_ci
    ON public.account (lower(btrim(username)));


-- Store only a one-way SHA-256 token hash, never the invitation/reset token.
-- A token lives for at most 30 minutes and can end by consumption or revocation,
-- but never both. V007's "active token" index does not inspect expires_at:
-- an expired token must still be consumed or revoked before issuing a new one.
CREATE TABLE public.account_credential_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    purpose TEXT NOT NULL,
    token_hash TEXT NOT NULL,
    issued_by_account_id BIGINT NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT uq_account_credential_token_hash
        UNIQUE (token_hash),
    CONSTRAINT fk_account_credential_token_account
        FOREIGN KEY (account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_account_credential_token_issuer
        FOREIGN KEY (issued_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_account_credential_token_purpose
        CHECK (purpose IN ('INVITATION', 'RESET')),
    CONSTRAINT ck_account_credential_token_hash
        CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_account_credential_token_expiry
        CHECK (
            expires_at > issued_at
            AND expires_at <= issued_at + INTERVAL '30 minutes'
        ),
    CONSTRAINT ck_account_credential_token_consumed
        CHECK (
            consumed_at IS NULL
            OR (consumed_at >= issued_at AND consumed_at <= expires_at)
        ),
    CONSTRAINT ck_account_credential_token_revoked
        CHECK (revoked_at IS NULL OR revoked_at >= issued_at),
    CONSTRAINT ck_account_credential_token_terminal
        CHECK (NOT (consumed_at IS NOT NULL AND revoked_at IS NOT NULL))
);

-- Revocation closes a role assignment without deleting its history. The partial
-- unique index in V007 allows only one currently active copy of the same role.
CREATE TABLE public.account_department_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    role TEXT NOT NULL,
    assigned_by_account_id BIGINT,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT fk_dept_role_account
        FOREIGN KEY (account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_dept_role_department
        FOREIGN KEY (department_id)
        REFERENCES public.department (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_dept_role_assigned_by
        FOREIGN KEY (assigned_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_dept_role_value
        CHECK (role = 'DEPARTMENT_ADMIN'),
    CONSTRAINT ck_dept_role_period
        CHECK (revoked_at IS NULL OR revoked_at >= assigned_at)
);
