-- Department memberships, NFC cards, card assignments, and devices.
-- Cross-scope FKs, partial unique indexes, and lookup indexes are added in V007.

CREATE TABLE public.department_membership (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMPTZ,
    created_by_account_id BIGINT,
    ended_by_account_id BIGINT,
    end_reason TEXT,
    CONSTRAINT uq_membership_scope
        UNIQUE (id, department_id, member_id),
    CONSTRAINT fk_membership_department
        FOREIGN KEY (department_id)
        REFERENCES public.department (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_membership_member
        FOREIGN KEY (member_id)
        REFERENCES public.member (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_membership_created_by
        FOREIGN KEY (created_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_membership_ended_by
        FOREIGN KEY (ended_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_membership_period
        CHECK (ended_at IS NULL OR ended_at >= joined_at),
    CONSTRAINT ck_membership_end_state
        CHECK (
            (ended_at IS NULL
                AND ended_by_account_id IS NULL
                AND end_reason IS NULL)
            OR
            (ended_at IS NOT NULL
                AND ended_by_account_id IS NOT NULL
                AND end_reason IS NOT NULL
                AND char_length(btrim(end_reason)) > 0)
        )
);


CREATE TABLE public.nfc_card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'AVAILABLE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_nfc_card_uid
        UNIQUE (uid),
    CONSTRAINT uq_nfc_card_identity
        UNIQUE (id, uid),
    CONSTRAINT ck_nfc_card_uid
        CHECK (
            uid ~ '^[0-9A-F]+$'
            AND char_length(uid) BETWEEN 8 AND 32
            AND mod(char_length(uid), 2) = 0
        ),
    CONSTRAINT ck_nfc_card_status
        CHECK (status IN ('AVAILABLE', 'ACTIVE', 'LOST', 'RETIRED'))
);


CREATE TABLE public.nfc_card_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nfc_card_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    membership_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    assigned_by_account_id BIGINT,
    unassigned_by_account_id BIGINT,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    unassigned_at TIMESTAMPTZ,
    end_reason TEXT,
    CONSTRAINT fk_card_assignment_card
        FOREIGN KEY (nfc_card_id)
        REFERENCES public.nfc_card (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_card_assignment_member
        FOREIGN KEY (member_id)
        REFERENCES public.member (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_card_assignment_assigned_by
        FOREIGN KEY (assigned_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_card_assignment_unassigned_by
        FOREIGN KEY (unassigned_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_card_assignment_period
        CHECK (unassigned_at IS NULL OR unassigned_at >= assigned_at),
    CONSTRAINT ck_card_assignment_end_state
        CHECK (
            (unassigned_at IS NULL
                AND unassigned_by_account_id IS NULL
                AND end_reason IS NULL)
            OR
            (unassigned_at IS NOT NULL
                AND unassigned_by_account_id IS NOT NULL
                AND end_reason IS NOT NULL
                AND char_length(btrim(end_reason)) > 0)
        )
);


CREATE TABLE public.device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    device_code TEXT NOT NULL,
    name TEXT NOT NULL,
    credential_hash TEXT NOT NULL,
    credential_version INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'INACTIVE',
    credential_issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    credential_tested_version INTEGER,
    credential_tested_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_device_code
        UNIQUE (device_code),
    CONSTRAINT uq_device_scope
        UNIQUE (id, department_id),
    CONSTRAINT fk_device_department
        FOREIGN KEY (department_id)
        REFERENCES public.department (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_device_code
        CHECK (
            device_code = btrim(device_code)
            AND char_length(device_code) BETWEEN 1 AND 100
        ),
    CONSTRAINT ck_device_name
        CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT ck_device_credential_hash
        CHECK (char_length(credential_hash) > 0),
    CONSTRAINT ck_device_credential_version
        CHECK (credential_version > 0),
    CONSTRAINT ck_device_credential_test
        CHECK (
            (credential_tested_version IS NULL
                AND credential_tested_at IS NULL)
            OR
            (credential_tested_version IS NOT NULL
                AND credential_tested_version = credential_version
                AND credential_tested_at IS NOT NULL
                AND credential_tested_at >= credential_issued_at)
        ),
    CONSTRAINT ck_device_active_credential_test
        CHECK (
            status <> 'ACTIVE'
            OR
            (credential_tested_version IS NOT NULL
                AND credential_tested_version = credential_version
                AND credential_tested_at IS NOT NULL
                AND credential_tested_at >= credential_issued_at)
        ),
    CONSTRAINT ck_device_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'REVOKED'))
);
