-- Versioned department attendance policies and their ordered result bands.
-- FK lookup indexes are added in V007.

CREATE TABLE public.attendance_policy_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    version_no INTEGER NOT NULL,
    name TEXT NOT NULL,
    check_in_start_time TIME WITHOUT TIME ZONE NOT NULL,
    status TEXT NOT NULL DEFAULT 'DRAFT',
    created_by_account_id BIGINT NOT NULL,
    published_by_account_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ,
    CONSTRAINT uq_policy_department_version
        UNIQUE (department_id, version_no),
    CONSTRAINT uq_policy_scope
        UNIQUE (id, department_id),
    CONSTRAINT fk_policy_department
        FOREIGN KEY (department_id)
        REFERENCES public.department (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_policy_created_by
        FOREIGN KEY (created_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_policy_published_by
        FOREIGN KEY (published_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_policy_version_no
        CHECK (version_no > 0),
    CONSTRAINT ck_policy_name
        CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT ck_policy_status
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'RETIRED')),
    CONSTRAINT ck_policy_publish_fields
        CHECK (
            (status = 'DRAFT'
                AND published_by_account_id IS NULL
                AND published_at IS NULL)
            OR
            (status IN ('PUBLISHED', 'RETIRED')
                AND published_by_account_id IS NOT NULL
                AND published_at IS NOT NULL)
        )
);


CREATE TABLE public.attendance_band (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_version_id BIGINT NOT NULL,
    sequence_no SMALLINT NOT NULL,
    label TEXT NOT NULL,
    parent_status TEXT NOT NULL,
    upper_time TIME WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_band_policy
        FOREIGN KEY (policy_version_id)
        REFERENCES public.attendance_policy_version (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_band_sequence
        UNIQUE (policy_version_id, sequence_no),
    CONSTRAINT uq_band_upper_time
        UNIQUE (policy_version_id, upper_time),
    CONSTRAINT uq_band_policy_status_scope
        UNIQUE (id, policy_version_id, parent_status),
    CONSTRAINT ck_band_sequence
        CHECK (sequence_no > 0),
    CONSTRAINT ck_band_label
        CHECK (char_length(btrim(label)) > 0),
    CONSTRAINT ck_band_parent_status
        CHECK (parent_status IN ('PRESENT', 'LATE'))
);
