CREATE TABLE public.attendance_day (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    attendance_date DATE NOT NULL,
    policy_version_id BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'SCHEDULED',
    created_by_account_id BIGINT NOT NULL,
    canceled_by_account_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalized_at TIMESTAMPTZ,
    canceled_at TIMESTAMPTZ,
    cancel_reason TEXT,
    CONSTRAINT uq_attendance_day_department_date
        UNIQUE (department_id, attendance_date),
    CONSTRAINT uq_attendance_day_scope
        UNIQUE (id, department_id),
    CONSTRAINT uq_attendance_day_policy_scope
        UNIQUE (id, policy_version_id),
    CONSTRAINT fk_attendance_day_department
        FOREIGN KEY (department_id)
        REFERENCES public.department (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_attendance_day_created_by
        FOREIGN KEY (created_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_attendance_day_canceled_by
        FOREIGN KEY (canceled_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_attendance_day_status
        CHECK (status IN ('SCHEDULED', 'FINALIZED', 'CANCELED')),
    CONSTRAINT ck_attendance_day_state_fields
        CHECK (
            (status = 'SCHEDULED'
                AND finalized_at IS NULL
                AND canceled_at IS NULL
                AND canceled_by_account_id IS NULL
                AND cancel_reason IS NULL)
            OR
            (status = 'FINALIZED'
                AND finalized_at IS NOT NULL
                AND canceled_at IS NULL
                AND canceled_by_account_id IS NULL
                AND cancel_reason IS NULL)
            OR
            (status = 'CANCELED'
                AND finalized_at IS NULL
                AND canceled_at IS NOT NULL
                AND canceled_by_account_id IS NOT NULL
                AND cancel_reason IS NOT NULL
                AND char_length(btrim(cancel_reason)) > 0)
        )
);

CREATE TABLE public.attendance_target (
    attendance_day_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    membership_id BIGINT NOT NULL,
    is_target BOOLEAN NOT NULL DEFAULT TRUE,
    added_source TEXT NOT NULL DEFAULT 'SNAPSHOT',
    changed_by_account_id BIGINT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    change_reason TEXT,
    CONSTRAINT pk_attendance_target
        PRIMARY KEY (attendance_day_id, member_id),
    CONSTRAINT fk_target_member
        FOREIGN KEY (member_id)
        REFERENCES public.member (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_target_changed_by
        FOREIGN KEY (changed_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_target_added_source
        CHECK (added_source IN ('SNAPSHOT', 'MANUAL')),
    CONSTRAINT ck_target_change_metadata
        CHECK (
            (added_source = 'SNAPSHOT'
                AND is_target
                AND changed_by_account_id IS NULL
                AND change_reason IS NULL)
            OR
            (changed_by_account_id IS NOT NULL
                AND change_reason IS NOT NULL
                AND char_length(btrim(change_reason)) > 0)
        )
);

CREATE TABLE public.attendance_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_day_id BIGINT NOT NULL,
    policy_version_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    attendance_band_id BIGINT,
    status TEXT NOT NULL,
    band_sequence_snapshot SMALLINT,
    band_label_snapshot TEXT,
    checked_in_at TIMESTAMPTZ,
    source TEXT NOT NULL,
    note TEXT,
    created_by_account_id BIGINT,
    updated_by_account_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_attendance_record_day_member
        UNIQUE (attendance_day_id, member_id),
    CONSTRAINT uq_attendance_record_day_scope
        UNIQUE (id, attendance_day_id),
    CONSTRAINT fk_record_target
        FOREIGN KEY (attendance_day_id, member_id)
        REFERENCES public.attendance_target (attendance_day_id, member_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_record_day_policy
        FOREIGN KEY (attendance_day_id, policy_version_id)
        REFERENCES public.attendance_day (id, policy_version_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_record_band_policy_status
        FOREIGN KEY (
            attendance_band_id,
            policy_version_id,
            status
        )
        REFERENCES public.attendance_band (
            id,
            policy_version_id,
            parent_status
        )
        ON DELETE RESTRICT,
    CONSTRAINT fk_record_created_by
        FOREIGN KEY (created_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_record_updated_by
        FOREIGN KEY (updated_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_record_status
        CHECK (status IN ('PRESENT', 'LATE', 'ABSENT')),
    CONSTRAINT ck_record_source
        CHECK (source IN ('NFC', 'AUTO_ABSENCE', 'MANUAL')),
    CONSTRAINT ck_record_source_status
        CHECK (
            (source = 'NFC' AND status IN ('PRESENT', 'LATE'))
            OR (source = 'AUTO_ABSENCE' AND status = 'ABSENT')
            OR source = 'MANUAL'
        ),
    CONSTRAINT ck_record_manual_actor
        CHECK (
            (source = 'MANUAL'
                AND (created_by_account_id IS NOT NULL
                    OR updated_by_account_id IS NOT NULL))
            OR
            (source <> 'MANUAL'
                AND created_by_account_id IS NULL)
        ),
    CONSTRAINT ck_record_band_snapshot
        CHECK (
            (status IN ('PRESENT', 'LATE')
                AND attendance_band_id IS NOT NULL
                AND band_sequence_snapshot IS NOT NULL
                AND band_sequence_snapshot > 0
                AND band_label_snapshot IS NOT NULL
                AND char_length(btrim(band_label_snapshot)) > 0
                AND checked_in_at IS NOT NULL)
            OR
            (status = 'ABSENT'
                AND attendance_band_id IS NULL
                AND band_sequence_snapshot IS NULL
                AND band_label_snapshot IS NULL
                AND checked_in_at IS NULL)
        )
);
