CREATE TABLE public.tag_event_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    uid TEXT NOT NULL,
    nfc_card_id BIGINT,
    attendance_day_id BIGINT,
    attendance_record_id BIGINT,
    result_code TEXT NOT NULL,
    http_status INTEGER,
    response_body JSONB,
    failure_type TEXT,
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_tag_event_device_request
        UNIQUE (device_id, request_id),
    CONSTRAINT fk_tag_event_card
        FOREIGN KEY (nfc_card_id, uid)
        REFERENCES public.nfc_card (id, uid)
        ON DELETE RESTRICT,
    CONSTRAINT ck_tag_event_request_id
        CHECK (request_id ~ '^[A-Za-z0-9_-]{1,64}$'),
    CONSTRAINT ck_tag_event_uid
        CHECK (
            uid ~ '^[0-9A-F]+$'
            AND char_length(uid) BETWEEN 8 AND 32
            AND mod(char_length(uid), 2) = 0
        ),
    CONSTRAINT ck_tag_event_result_code
        CHECK (
            result_code IN (
                'PROCESSING',
                'CHECKED_IN',
                'LATE',
                'ALREADY_CHECKED_IN',
                'UNKNOWN_UID',
                'INACTIVE_CARD',
                'NOT_DEPARTMENT_MEMBER',
                'NO_ATTENDANCE_DAY',
                'NOT_ATTENDANCE_TARGET',
                'CHECK_IN_NOT_OPEN',
                'CHECK_IN_CLOSED'
            )
        ),
    CONSTRAINT ck_tag_event_record_day
        CHECK (
            attendance_record_id IS NULL
            OR attendance_day_id IS NOT NULL
        ),
    CONSTRAINT ck_tag_event_response
        CHECK (
            (result_code = 'PROCESSING'
                AND http_status IS NULL
                AND response_body IS NULL)
            OR
            (result_code <> 'PROCESSING'
                AND http_status IS NOT NULL
                AND http_status BETWEEN 100 AND 599
                AND response_body IS NOT NULL)
        )
);

CREATE TABLE public.audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT,
    actor_type TEXT NOT NULL,
    actor_account_id BIGINT,
    actor_device_id BIGINT,
    attendance_day_id BIGINT,
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    before_data JSONB,
    after_data JSONB,
    reason TEXT,
    idempotency_key TEXT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_audit_idempotency_key
        UNIQUE (idempotency_key),
    CONSTRAINT fk_audit_department
        FOREIGN KEY (department_id)
        REFERENCES public.department (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_audit_actor_account
        FOREIGN KEY (actor_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_audit_actor
        CHECK (
            (actor_type = 'ACCOUNT'
                AND actor_account_id IS NOT NULL
                AND actor_device_id IS NULL)
            OR
            (actor_type = 'DEVICE'
                AND actor_account_id IS NULL
                AND actor_device_id IS NOT NULL
                AND department_id IS NOT NULL)
            OR
            (actor_type = 'SYSTEM'
                AND actor_account_id IS NULL
                AND actor_device_id IS NULL)
        ),
    CONSTRAINT ck_audit_day_department
        CHECK (
            (attendance_day_id IS NULL AND department_id IS NULL)
            OR
            (attendance_day_id IS NULL AND department_id IS NOT NULL)
            OR
            (attendance_day_id IS NOT NULL AND department_id IS NOT NULL)
        ),
    CONSTRAINT ck_audit_action
        CHECK (char_length(btrim(action)) > 0),
    CONSTRAINT ck_audit_target_type
        CHECK (char_length(btrim(target_type)) > 0),
    CONSTRAINT ck_audit_target_id
        CHECK (char_length(btrim(target_id)) > 0),
    CONSTRAINT ck_audit_reason
        CHECK (reason IS NULL OR char_length(btrim(reason)) > 0),
    CONSTRAINT ck_audit_idempotency_key
        CHECK (
            idempotency_key IS NULL
            OR char_length(btrim(idempotency_key)) > 0
        )
);
