-- Same-day attendance finalization and Telegram notification delivery.
-- Telegram credentials never belong in this schema; only a connected private
-- chat identifier and one-way link-token hashes are retained.

ALTER TABLE public.attendance_day
    ADD COLUMN finalization_due_at TIMESTAMPTZ;

UPDATE public.attendance_day AS day
SET finalization_due_at = (
    day.attendance_date + (
        SELECT max(band.upper_time)
        FROM public.attendance_band AS band
        WHERE band.policy_version_id = day.policy_version_id
    )
) AT TIME ZONE 'Asia/Seoul';

ALTER TABLE public.attendance_day
    ALTER COLUMN finalization_due_at SET NOT NULL;

-- Application writes always supply the policy-derived value. This default keeps
-- guarded legacy imports and fixture inserts compatible until they can supply a
-- frozen policy close time themselves.
ALTER TABLE public.attendance_day
    ALTER COLUMN finalization_due_at SET DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX idx_attendance_day_due_finalization
    ON public.attendance_day (finalization_due_at, id)
    WHERE status = 'SCHEDULED';

CREATE TABLE public.telegram_link_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    token_hash TEXT NOT NULL UNIQUE,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT fk_telegram_link_token_account
        FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE RESTRICT,
    CONSTRAINT ck_telegram_link_token_hash
        CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_telegram_link_token_expiry
        CHECK (expires_at > issued_at AND expires_at <= issued_at + INTERVAL '15 minutes'),
    CONSTRAINT ck_telegram_link_token_terminal
        CHECK (NOT (consumed_at IS NOT NULL AND revoked_at IS NOT NULL))
);

CREATE UNIQUE INDEX uq_telegram_link_token_active_account
    ON public.telegram_link_token (account_id)
    WHERE consumed_at IS NULL AND revoked_at IS NULL;

CREATE TABLE public.account_telegram_connection (
    account_id BIGINT PRIMARY KEY,
    chat_id BIGINT NOT NULL UNIQUE,
    telegram_user_id BIGINT NOT NULL UNIQUE,
    linked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_account_telegram_connection_account
        FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE RESTRICT
);

CREATE TABLE public.telegram_webhook_update (
    update_id BIGINT PRIMARY KEY,
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE public.attendance_notification_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_type TEXT NOT NULL,
    attendance_day_id BIGINT,
    department_id BIGINT,
    account_id BIGINT NOT NULL,
    message_text TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_until TIMESTAMPTZ,
    telegram_message_id BIGINT,
    sent_at TIMESTAMPTZ,
    last_error_code TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notification_day
        FOREIGN KEY (attendance_day_id) REFERENCES public.attendance_day(id) ON DELETE RESTRICT,
    CONSTRAINT fk_notification_department
        FOREIGN KEY (department_id) REFERENCES public.department(id) ON DELETE RESTRICT,
    CONSTRAINT fk_notification_account
        FOREIGN KEY (account_id) REFERENCES public.account(id) ON DELETE RESTRICT,
    CONSTRAINT ck_notification_type
        CHECK (notification_type IN ('ATTENDANCE_DAY_FINALIZED', 'TELEGRAM_CONNECTION_TEST')),
    CONSTRAINT ck_notification_scope
        CHECK (
            (notification_type = 'ATTENDANCE_DAY_FINALIZED'
                AND attendance_day_id IS NOT NULL AND department_id IS NOT NULL)
            OR
            (notification_type = 'TELEGRAM_CONNECTION_TEST'
                AND attendance_day_id IS NULL AND department_id IS NULL)
        ),
    CONSTRAINT ck_notification_message_length
        CHECK (char_length(message_text) BETWEEN 1 AND 4096),
    CONSTRAINT ck_notification_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'RETRY', 'SENT', 'DEAD', 'CANCELED')),
    CONSTRAINT ck_notification_attempt_count CHECK (attempt_count >= 0)
);

CREATE UNIQUE INDEX uq_attendance_finalized_notification_recipient
    ON public.attendance_notification_outbox(notification_type, attendance_day_id, account_id)
    WHERE notification_type = 'ATTENDANCE_DAY_FINALIZED';

CREATE INDEX idx_notification_outbox_dispatch
    ON public.attendance_notification_outbox(status, next_attempt_at, id)
    WHERE status IN ('PENDING', 'RETRY');

CREATE INDEX idx_notification_outbox_account
    ON public.attendance_notification_outbox(account_id, status, id);
