-- Persist the first failure timestamp and a delivery-fenced operational alert
-- outbox. Runtime messages contain only non-personal incident metadata.
ALTER TABLE public.attendance_day
    ADD COLUMN finalization_first_failed_at TIMESTAMPTZ;

UPDATE public.attendance_day
SET finalization_first_failed_at = NULL,
    finalization_last_failed_at = NULL
WHERE finalization_failure_count = 0;

-- V014 did not require a failure timestamp. CURRENT_TIMESTAMP is the only
-- honest durable fallback when an older row has already lost that detail.
UPDATE public.attendance_day
SET finalization_first_failed_at = COALESCE(
        finalization_first_failed_at,
        finalization_last_failed_at,
        CURRENT_TIMESTAMP
    ),
    finalization_last_failed_at = COALESCE(
        finalization_last_failed_at,
        CURRENT_TIMESTAMP
    )
WHERE finalization_failure_count > 0;

ALTER TABLE public.attendance_day
    ADD CONSTRAINT ck_attendance_day_finalization_failure_timestamps
        CHECK (
            (finalization_failure_count = 0
                AND finalization_first_failed_at IS NULL
                AND finalization_last_failed_at IS NULL)
            OR
            (finalization_failure_count > 0
                AND finalization_first_failed_at IS NOT NULL
                AND finalization_last_failed_at IS NOT NULL
                AND finalization_first_failed_at <= finalization_last_failed_at)
        ) NOT VALID;

ALTER TABLE public.attendance_day
    VALIDATE CONSTRAINT ck_attendance_day_finalization_failure_timestamps;

CREATE TABLE public.finalization_operational_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,
    attendance_day_id BIGINT NOT NULL,
    incident_claim_version BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    department_name TEXT NOT NULL,
    attendance_date DATE NOT NULL,
    first_failed_at TIMESTAMPTZ NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    total_attempt_count INTEGER NOT NULL,
    error_code VARCHAR(80) NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    delivery_attempt_count INTEGER NOT NULL DEFAULT 0,
    delivery_claim_version BIGINT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_until TIMESTAMPTZ,
    telegram_message_id BIGINT,
    sent_at TIMESTAMPTZ,
    last_delivery_error_code VARCHAR(80),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_finalization_operational_event_incident
        UNIQUE (event_type, attendance_day_id, incident_claim_version),
    CONSTRAINT fk_finalization_operational_event_day
        FOREIGN KEY (attendance_day_id)
        REFERENCES public.attendance_day (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_finalization_operational_event_department
        FOREIGN KEY (department_id)
        REFERENCES public.department (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_finalization_operational_event_type
        CHECK (event_type = 'FINALIZATION_RETRY_EXHAUSTED'),
    CONSTRAINT ck_finalization_operational_event_department_name
        CHECK (char_length(btrim(department_name)) > 0),
    CONSTRAINT ck_finalization_operational_event_attempts
        CHECK (total_attempt_count = 6 AND delivery_attempt_count >= 0),
    CONSTRAINT ck_finalization_operational_event_claim_versions
        CHECK (incident_claim_version >= 0 AND delivery_claim_version >= 0),
    CONSTRAINT ck_finalization_operational_event_error_code
        CHECK (char_length(btrim(error_code)) > 0),
    CONSTRAINT ck_finalization_operational_event_time_order
        CHECK (first_failed_at <= occurred_at),
    CONSTRAINT ck_finalization_operational_event_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'RETRY', 'SENT')),
    CONSTRAINT ck_finalization_operational_event_delivery_state
        CHECK (
            (status IN ('PENDING', 'RETRY')
                AND lease_until IS NULL
                AND telegram_message_id IS NULL
                AND sent_at IS NULL)
            OR
            (status = 'PROCESSING'
                AND lease_until IS NOT NULL
                AND telegram_message_id IS NULL
                AND sent_at IS NULL)
            OR
            (status = 'SENT'
                AND lease_until IS NULL
                AND telegram_message_id IS NOT NULL
                AND telegram_message_id > 0
                AND sent_at IS NOT NULL)
    )
);

-- Dates that exhausted all attempts before this release cannot produce the
-- application event again. Seed their durable alerts so startup recovery sends
-- them after the upgraded application becomes ready.
INSERT INTO public.finalization_operational_event (
    event_type,
    attendance_day_id,
    incident_claim_version,
    department_id,
    department_name,
    attendance_date,
    first_failed_at,
    occurred_at,
    total_attempt_count,
    error_code,
    next_attempt_at
)
SELECT
    'FINALIZATION_RETRY_EXHAUSTED',
    day.id,
    day.finalization_claim_version,
    day.department_id,
    department.name,
    day.attendance_date,
    day.finalization_first_failed_at,
    day.finalization_last_failed_at,
    6,
    COALESCE(
        NULLIF(btrim(day.finalization_last_error_code), ''),
        'UNKNOWN_FINALIZATION_ERROR'
    ),
    CURRENT_TIMESTAMP
FROM public.attendance_day AS day
JOIN public.department AS department ON department.id = day.department_id
WHERE day.status = 'SCHEDULED'
  AND day.finalization_failure_count = 6;

CREATE INDEX idx_finalization_operational_event_dispatch
    ON public.finalization_operational_event (next_attempt_at, id)
    WHERE status IN ('PENDING', 'RETRY');

CREATE INDEX idx_finalization_operational_event_lease
    ON public.finalization_operational_event (lease_until, id)
    WHERE status = 'PROCESSING';
