-- Durable SMTP delivery jobs. The raw credential token is deliberately absent:
-- each invitation delivery attempt creates a fresh one-time token in memory.
CREATE TABLE public.department_admin_invitation_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL REFERENCES public.account(id) ON DELETE RESTRICT,
    department_id BIGINT NOT NULL REFERENCES public.department(id) ON DELETE RESTRICT,
    issued_by_account_id BIGINT NOT NULL REFERENCES public.account(id) ON DELETE RESTRICT,
    delivery_type TEXT NOT NULL,
    recipient_email TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    claim_version BIGINT NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_until TIMESTAMPTZ,
    sent_at TIMESTAMPTZ,
    last_error_code TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_department_admin_invitation_delivery_type
        CHECK (delivery_type IN ('INVITATION', 'ROLE_ASSIGNED')),
    CONSTRAINT ck_department_admin_invitation_recipient
        CHECK (char_length(btrim(recipient_email)) > 0),
    CONSTRAINT ck_department_admin_invitation_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'RETRY', 'SENT', 'DEAD', 'CANCELED')),
    CONSTRAINT ck_department_admin_invitation_attempt_count
        CHECK (attempt_count >= 0),
    CONSTRAINT ck_department_admin_invitation_claim_version
        CHECK (claim_version >= 0)
);

CREATE INDEX idx_department_admin_invitation_dispatch
    ON public.department_admin_invitation_outbox(status, next_attempt_at, id)
    WHERE status IN ('PENDING', 'RETRY');

CREATE INDEX idx_department_admin_invitation_lease
    ON public.department_admin_invitation_outbox(lease_until, id)
    WHERE status = 'PROCESSING';

CREATE INDEX idx_department_admin_invitation_department
    ON public.department_admin_invitation_outbox(department_id, status, id);
