-- A schedule is the administrator-facing attendance policy.  It owns the
-- recurrence and ON/OFF state, while policy versions remain immutable
-- snapshots referenced by actual attendance days.
CREATE TABLE public.attendance_policy_schedule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    policy_version_id BIGINT NOT NULL UNIQUE,
    status TEXT NOT NULL DEFAULT 'ON',
    start_date DATE NOT NULL,
    end_date DATE,
    recurrence TEXT NOT NULL,
    interval_value INTEGER NOT NULL DEFAULT 1,
    yearly_month SMALLINT,
    yearly_day SMALLINT,
    created_by_account_id BIGINT NOT NULL,
    updated_by_account_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    archived_at TIMESTAMPTZ,
    CONSTRAINT fk_policy_schedule_department
        FOREIGN KEY (department_id) REFERENCES public.department (id) ON DELETE RESTRICT,
    CONSTRAINT fk_policy_schedule_version
        FOREIGN KEY (policy_version_id) REFERENCES public.attendance_policy_version (id) ON DELETE RESTRICT,
    CONSTRAINT fk_policy_schedule_created_by
        FOREIGN KEY (created_by_account_id) REFERENCES public.account (id) ON DELETE RESTRICT,
    CONSTRAINT fk_policy_schedule_updated_by
        FOREIGN KEY (updated_by_account_id) REFERENCES public.account (id) ON DELETE RESTRICT,
    CONSTRAINT ck_policy_schedule_status
        CHECK (status IN ('ON', 'OFF', 'ARCHIVED')),
    CONSTRAINT ck_policy_schedule_dates
        CHECK (end_date IS NULL OR end_date >= start_date),
    CONSTRAINT ck_policy_schedule_recurrence
        CHECK (recurrence IN ('NONE', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY')),
    CONSTRAINT ck_policy_schedule_interval
        CHECK (interval_value > 0),
    CONSTRAINT ck_policy_schedule_yearly_date
        CHECK ((recurrence = 'YEARLY' AND yearly_month BETWEEN 1 AND 12 AND yearly_day BETWEEN 1 AND 31)
            OR (recurrence <> 'YEARLY' AND yearly_month IS NULL AND yearly_day IS NULL)),
    CONSTRAINT ck_policy_schedule_archive
        CHECK ((status = 'ARCHIVED' AND archived_at IS NOT NULL)
            OR (status <> 'ARCHIVED' AND archived_at IS NULL))
);

CREATE TABLE public.attendance_policy_schedule_weekday (
    schedule_id BIGINT NOT NULL,
    weekday SMALLINT NOT NULL,
    PRIMARY KEY (schedule_id, weekday),
    CONSTRAINT fk_policy_schedule_weekday_schedule
        FOREIGN KEY (schedule_id) REFERENCES public.attendance_policy_schedule (id) ON DELETE RESTRICT,
    CONSTRAINT ck_policy_schedule_weekday CHECK (weekday BETWEEN 1 AND 7)
);

CREATE TABLE public.attendance_policy_schedule_monthday (
    schedule_id BIGINT NOT NULL,
    monthday SMALLINT NOT NULL,
    PRIMARY KEY (schedule_id, monthday),
    CONSTRAINT fk_policy_schedule_monthday_schedule
        FOREIGN KEY (schedule_id) REFERENCES public.attendance_policy_schedule (id) ON DELETE RESTRICT,
    CONSTRAINT ck_policy_schedule_monthday CHECK (monthday BETWEEN 1 AND 31)
);

ALTER TABLE public.attendance_day
    ADD COLUMN policy_schedule_id BIGINT,
    ADD CONSTRAINT fk_attendance_day_policy_schedule
        FOREIGN KEY (policy_schedule_id)
        REFERENCES public.attendance_policy_schedule (id)
        ON DELETE RESTRICT;

CREATE INDEX idx_policy_schedule_department_status
    ON public.attendance_policy_schedule (department_id, status, start_date);

CREATE INDEX idx_attendance_day_policy_schedule
    ON public.attendance_day (policy_schedule_id, attendance_date)
    WHERE policy_schedule_id IS NOT NULL;
