-- Attend MVP target schema for a fresh database.
-- Target: PostgreSQL 15+
-- Legacy databases adopt and extend the existing member table through the
-- guarded Flyway path in MIGRATION_PLAN.md. This reference DDL does not drop
-- or migrate authentications/attendance/attendance_log.

BEGIN;

CREATE TABLE public.department (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_department_name
        CHECK (char_length(btrim(name)) > 0)
);

CREATE UNIQUE INDEX uq_department_name_ci
    ON public.department (lower(btrim(name)));


CREATE TABLE public.account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL,
    password_hash TEXT,
    system_role TEXT,
    status TEXT NOT NULL DEFAULT 'PENDING_SETUP',
    password_changed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_account_username
        CHECK (char_length(btrim(username)) > 0),
    CONSTRAINT ck_account_password_hash
        CHECK (password_hash IS NULL OR char_length(password_hash) > 0),
    CONSTRAINT ck_account_system_role
        CHECK (system_role IS NULL OR system_role = 'SYSTEM_ADMIN'),
    CONSTRAINT ck_account_setup_state
        CHECK (
            (status = 'PENDING_SETUP'
                AND password_hash IS NULL
                AND password_changed_at IS NULL)
            OR
            (status = 'ACTIVE'
                AND password_hash IS NOT NULL
                AND password_changed_at IS NOT NULL)
            OR
            (status = 'DISABLED'
                AND (
                    (password_hash IS NULL AND password_changed_at IS NULL)
                    OR
                    (password_hash IS NOT NULL AND password_changed_at IS NOT NULL)
                ))
        ),
    CONSTRAINT ck_account_status
        CHECK (status IN ('PENDING_SETUP', 'ACTIVE', 'DISABLED'))
);

CREATE UNIQUE INDEX uq_account_username_ci
    ON public.account (lower(btrim(username)));


CREATE TABLE public.account_credential_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    purpose TEXT NOT NULL,
    token_hash TEXT NOT NULL,
    issued_by_account_id BIGINT NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT uq_account_credential_token_hash
        UNIQUE (token_hash),
    CONSTRAINT fk_account_credential_token_account
        FOREIGN KEY (account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_account_credential_token_issuer
        FOREIGN KEY (issued_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_account_credential_token_purpose
        CHECK (purpose IN ('INVITATION', 'RESET')),
    CONSTRAINT ck_account_credential_token_hash
        CHECK (token_hash ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_account_credential_token_expiry
        CHECK (
            expires_at > issued_at
            AND expires_at <= issued_at + INTERVAL '30 minutes'
        ),
    CONSTRAINT ck_account_credential_token_consumed
        CHECK (
            consumed_at IS NULL
            OR (consumed_at >= issued_at AND consumed_at <= expires_at)
        ),
    CONSTRAINT ck_account_credential_token_revoked
        CHECK (revoked_at IS NULL OR revoked_at >= issued_at),
    CONSTRAINT ck_account_credential_token_terminal
        CHECK (NOT (consumed_at IS NOT NULL AND revoked_at IS NOT NULL))
);

CREATE UNIQUE INDEX uq_account_credential_token_active
    ON public.account_credential_token (account_id, purpose)
    WHERE consumed_at IS NULL AND revoked_at IS NULL;

CREATE INDEX idx_account_credential_token_account
    ON public.account_credential_token (account_id);

CREATE INDEX idx_account_credential_token_issuer
    ON public.account_credential_token (issued_by_account_id);


CREATE TABLE public.account_department_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    role TEXT NOT NULL,
    assigned_by_account_id BIGINT,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMPTZ,
    CONSTRAINT fk_dept_role_account
        FOREIGN KEY (account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_dept_role_department
        FOREIGN KEY (department_id)
        REFERENCES public.department (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_dept_role_assigned_by
        FOREIGN KEY (assigned_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_dept_role_value
        CHECK (role = 'DEPARTMENT_ADMIN'),
    CONSTRAINT ck_dept_role_period
        CHECK (revoked_at IS NULL OR revoked_at >= assigned_at)
);

CREATE UNIQUE INDEX uq_dept_role_active
    ON public.account_department_role (account_id, department_id, role)
    WHERE revoked_at IS NULL;

CREATE INDEX idx_dept_role_department_account
    ON public.account_department_role (department_id, account_id);

CREATE INDEX idx_dept_role_account
    ON public.account_department_role (account_id);

CREATE INDEX idx_dept_role_assigned_by
    ON public.account_department_role (assigned_by_account_id)
    WHERE assigned_by_account_id IS NOT NULL;


CREATE TABLE public.member (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age INTEGER,
    phone VARCHAR(255),
    birth DATE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    card_uid VARCHAR(20) UNIQUE,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_member_name
        CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT ck_member_phone
        CHECK (phone IS NULL OR char_length(btrim(phone)) > 0)
);

COMMENT ON COLUMN public.member.age IS
    'Legacy column; not used by the new attendance domain.';
COMMENT ON COLUMN public.member.birth IS
    'Legacy column; not used by the new attendance domain.';
COMMENT ON COLUMN public.member.created_at IS
    'Legacy timestamp without time zone; not used for attendance decisions or statistics.';
COMMENT ON COLUMN public.member.card_uid IS
    'Legacy migration evidence only; nfc_card and nfc_card_assignment are the operational source of truth.';


CREATE TABLE public.department_membership (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ended_at TIMESTAMPTZ,
    created_by_account_id BIGINT,
    ended_by_account_id BIGINT,
    end_reason TEXT,
    CONSTRAINT uq_membership_scope
        UNIQUE (id, department_id, member_id),
    CONSTRAINT fk_membership_department
        FOREIGN KEY (department_id)
        REFERENCES public.department (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_membership_member
        FOREIGN KEY (member_id)
        REFERENCES public.member (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_membership_created_by
        FOREIGN KEY (created_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_membership_ended_by
        FOREIGN KEY (ended_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_membership_period
        CHECK (ended_at IS NULL OR ended_at >= joined_at),
    CONSTRAINT ck_membership_end_state
        CHECK (
            (ended_at IS NULL
                AND ended_by_account_id IS NULL
                AND end_reason IS NULL)
            OR
            (ended_at IS NOT NULL
                AND ended_by_account_id IS NOT NULL
                AND end_reason IS NOT NULL
                AND char_length(btrim(end_reason)) > 0)
        )
);

CREATE UNIQUE INDEX uq_membership_one_active_per_member
    ON public.department_membership (member_id)
    WHERE ended_at IS NULL;

CREATE UNIQUE INDEX uq_membership_active_in_department
    ON public.department_membership (department_id, member_id)
    WHERE ended_at IS NULL;

CREATE INDEX idx_membership_department_member
    ON public.department_membership (department_id, member_id);

CREATE INDEX idx_membership_member_joined
    ON public.department_membership (member_id, joined_at DESC);

CREATE INDEX idx_membership_created_by
    ON public.department_membership (created_by_account_id)
    WHERE created_by_account_id IS NOT NULL;

CREATE INDEX idx_membership_ended_by
    ON public.department_membership (ended_by_account_id)
    WHERE ended_by_account_id IS NOT NULL;


CREATE TABLE public.nfc_card (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uid TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'AVAILABLE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_nfc_card_uid
        UNIQUE (uid),
    CONSTRAINT uq_nfc_card_identity
        UNIQUE (id, uid),
    CONSTRAINT ck_nfc_card_uid
        CHECK (
            uid ~ '^[0-9A-F]+$'
            AND char_length(uid) BETWEEN 8 AND 32
            AND mod(char_length(uid), 2) = 0
        ),
    CONSTRAINT ck_nfc_card_status
        CHECK (status IN ('AVAILABLE', 'ACTIVE', 'LOST', 'RETIRED'))
);


CREATE TABLE public.nfc_card_assignment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nfc_card_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    membership_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    assigned_by_account_id BIGINT,
    unassigned_by_account_id BIGINT,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    unassigned_at TIMESTAMPTZ,
    end_reason TEXT,
    CONSTRAINT fk_card_assignment_card
        FOREIGN KEY (nfc_card_id)
        REFERENCES public.nfc_card (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_card_assignment_membership
        FOREIGN KEY (membership_id, department_id, member_id)
        REFERENCES public.department_membership (id, department_id, member_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_card_assignment_member
        FOREIGN KEY (member_id)
        REFERENCES public.member (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_card_assignment_assigned_by
        FOREIGN KEY (assigned_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_card_assignment_unassigned_by
        FOREIGN KEY (unassigned_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_card_assignment_period
        CHECK (unassigned_at IS NULL OR unassigned_at >= assigned_at),
    CONSTRAINT ck_card_assignment_end_state
        CHECK (
            (unassigned_at IS NULL
                AND unassigned_by_account_id IS NULL
                AND end_reason IS NULL)
            OR
            (unassigned_at IS NOT NULL
                AND unassigned_by_account_id IS NOT NULL
                AND end_reason IS NOT NULL
                AND char_length(btrim(end_reason)) > 0)
        )
);

CREATE UNIQUE INDEX uq_card_one_active_assignment
    ON public.nfc_card_assignment (nfc_card_id)
    WHERE unassigned_at IS NULL;

CREATE UNIQUE INDEX uq_member_one_active_card
    ON public.nfc_card_assignment (member_id)
    WHERE unassigned_at IS NULL;

CREATE INDEX idx_card_assignment_department_member
    ON public.nfc_card_assignment (department_id, member_id);

CREATE INDEX idx_card_assignment_card
    ON public.nfc_card_assignment (nfc_card_id);

CREATE INDEX idx_card_assignment_member
    ON public.nfc_card_assignment (member_id);

CREATE INDEX idx_card_assignment_membership
    ON public.nfc_card_assignment (membership_id);

CREATE INDEX idx_card_assignment_assigned_by
    ON public.nfc_card_assignment (assigned_by_account_id)
    WHERE assigned_by_account_id IS NOT NULL;

CREATE INDEX idx_card_assignment_unassigned_by
    ON public.nfc_card_assignment (unassigned_by_account_id)
    WHERE unassigned_by_account_id IS NOT NULL;


CREATE TABLE public.device (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    device_code TEXT NOT NULL,
    name TEXT NOT NULL,
    credential_hash TEXT NOT NULL,
    credential_version INTEGER NOT NULL DEFAULT 1,
    status TEXT NOT NULL DEFAULT 'INACTIVE',
    credential_issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    credential_tested_version INTEGER,
    credential_tested_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_device_code
        UNIQUE (device_code),
    CONSTRAINT uq_device_scope
        UNIQUE (id, department_id),
    CONSTRAINT fk_device_department
        FOREIGN KEY (department_id)
        REFERENCES public.department (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_device_code
        CHECK (
            device_code = btrim(device_code)
            AND char_length(device_code) BETWEEN 1 AND 100
        ),
    CONSTRAINT ck_device_name
        CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT ck_device_credential_hash
        CHECK (char_length(credential_hash) > 0),
    CONSTRAINT ck_device_credential_version
        CHECK (credential_version > 0),
    CONSTRAINT ck_device_credential_test
        CHECK (
            (credential_tested_version IS NULL
                AND credential_tested_at IS NULL)
            OR
            (credential_tested_version IS NOT NULL
                AND credential_tested_version = credential_version
                AND credential_tested_at IS NOT NULL
                AND credential_tested_at >= credential_issued_at)
        ),
    CONSTRAINT ck_device_active_credential_test
        CHECK (
            status <> 'ACTIVE'
            OR
            (credential_tested_version IS NOT NULL
                AND credential_tested_version = credential_version
                AND credential_tested_at IS NOT NULL
                AND credential_tested_at >= credential_issued_at)
        ),
    CONSTRAINT ck_device_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'REVOKED'))
);

CREATE INDEX idx_device_department_status
    ON public.device (department_id, status);


CREATE TABLE public.attendance_policy_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    version_no INTEGER NOT NULL,
    name TEXT NOT NULL,
    check_in_start_time TIME WITHOUT TIME ZONE NOT NULL,
    status TEXT NOT NULL DEFAULT 'DRAFT',
    created_by_account_id BIGINT NOT NULL,
    published_by_account_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMPTZ,
    CONSTRAINT uq_policy_department_version
        UNIQUE (department_id, version_no),
    CONSTRAINT uq_policy_scope
        UNIQUE (id, department_id),
    CONSTRAINT fk_policy_department
        FOREIGN KEY (department_id)
        REFERENCES public.department (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_policy_created_by
        FOREIGN KEY (created_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_policy_published_by
        FOREIGN KEY (published_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_policy_version_no
        CHECK (version_no > 0),
    CONSTRAINT ck_policy_name
        CHECK (char_length(btrim(name)) > 0),
    CONSTRAINT ck_policy_status
        CHECK (status IN ('DRAFT', 'PUBLISHED', 'RETIRED')),
    CONSTRAINT ck_policy_publish_fields
        CHECK (
            (status = 'DRAFT'
                AND published_by_account_id IS NULL
                AND published_at IS NULL)
            OR
            (status IN ('PUBLISHED', 'RETIRED')
                AND published_by_account_id IS NOT NULL
                AND published_at IS NOT NULL)
        )
);

CREATE INDEX idx_policy_department_status_version
    ON public.attendance_policy_version
        (department_id, status, version_no DESC);

CREATE INDEX idx_policy_created_by
    ON public.attendance_policy_version (created_by_account_id);

CREATE INDEX idx_policy_published_by
    ON public.attendance_policy_version (published_by_account_id)
    WHERE published_by_account_id IS NOT NULL;


CREATE TABLE public.attendance_band (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_version_id BIGINT NOT NULL,
    sequence_no SMALLINT NOT NULL,
    label TEXT NOT NULL,
    parent_status TEXT NOT NULL,
    upper_time TIME WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_band_policy
        FOREIGN KEY (policy_version_id)
        REFERENCES public.attendance_policy_version (id)
        ON DELETE RESTRICT,
    CONSTRAINT uq_band_sequence
        UNIQUE (policy_version_id, sequence_no),
    CONSTRAINT uq_band_upper_time
        UNIQUE (policy_version_id, upper_time),
    CONSTRAINT uq_band_policy_status_scope
        UNIQUE (id, policy_version_id, parent_status),
    CONSTRAINT ck_band_sequence
        CHECK (sequence_no > 0),
    CONSTRAINT ck_band_label
        CHECK (char_length(btrim(label)) > 0),
    CONSTRAINT ck_band_parent_status
        CHECK (parent_status IN ('PRESENT', 'LATE'))
);


CREATE TABLE public.attendance_day (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT NOT NULL,
    attendance_date DATE NOT NULL,
    policy_version_id BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'SCHEDULED',
    created_by_account_id BIGINT NOT NULL,
    canceled_by_account_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalized_at TIMESTAMPTZ,
    canceled_at TIMESTAMPTZ,
    cancel_reason TEXT,
    CONSTRAINT uq_attendance_day_department_date
        UNIQUE (department_id, attendance_date),
    CONSTRAINT uq_attendance_day_scope
        UNIQUE (id, department_id),
    CONSTRAINT uq_attendance_day_policy_scope
        UNIQUE (id, policy_version_id),
    CONSTRAINT fk_attendance_day_department
        FOREIGN KEY (department_id)
        REFERENCES public.department (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_attendance_day_policy
        FOREIGN KEY (policy_version_id, department_id)
        REFERENCES public.attendance_policy_version (id, department_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_attendance_day_created_by
        FOREIGN KEY (created_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_attendance_day_canceled_by
        FOREIGN KEY (canceled_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_attendance_day_status
        CHECK (status IN ('SCHEDULED', 'FINALIZED', 'CANCELED')),
    CONSTRAINT ck_attendance_day_state_fields
        CHECK (
            (status = 'SCHEDULED'
                AND finalized_at IS NULL
                AND canceled_at IS NULL
                AND canceled_by_account_id IS NULL
                AND cancel_reason IS NULL)
            OR
            (status = 'FINALIZED'
                AND finalized_at IS NOT NULL
                AND canceled_at IS NULL
                AND canceled_by_account_id IS NULL
                AND cancel_reason IS NULL)
            OR
            (status = 'CANCELED'
                AND finalized_at IS NULL
                AND canceled_at IS NOT NULL
                AND canceled_by_account_id IS NOT NULL
                AND cancel_reason IS NOT NULL
                AND char_length(btrim(cancel_reason)) > 0)
        )
);

CREATE INDEX idx_attendance_day_unfinalized
    ON public.attendance_day (attendance_date, id)
    WHERE status = 'SCHEDULED';

CREATE INDEX idx_attendance_day_policy_date
    ON public.attendance_day (policy_version_id, attendance_date DESC);

CREATE INDEX idx_attendance_day_created_by
    ON public.attendance_day (created_by_account_id);

CREATE INDEX idx_attendance_day_canceled_by
    ON public.attendance_day (canceled_by_account_id)
    WHERE canceled_by_account_id IS NOT NULL;


CREATE TABLE public.attendance_target (
    attendance_day_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    membership_id BIGINT NOT NULL,
    is_target BOOLEAN NOT NULL DEFAULT TRUE,
    added_source TEXT NOT NULL DEFAULT 'SNAPSHOT',
    changed_by_account_id BIGINT,
    changed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    change_reason TEXT,
    CONSTRAINT pk_attendance_target
        PRIMARY KEY (attendance_day_id, member_id),
    CONSTRAINT fk_target_day
        FOREIGN KEY (attendance_day_id, department_id)
        REFERENCES public.attendance_day (id, department_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_target_membership
        FOREIGN KEY (membership_id, department_id, member_id)
        REFERENCES public.department_membership (id, department_id, member_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_target_member
        FOREIGN KEY (member_id)
        REFERENCES public.member (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_target_changed_by
        FOREIGN KEY (changed_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_target_added_source
        CHECK (added_source IN ('SNAPSHOT', 'MANUAL')),
    CONSTRAINT ck_target_change_metadata
        CHECK (
            (added_source = 'SNAPSHOT'
                AND is_target
                AND changed_by_account_id IS NULL
                AND change_reason IS NULL)
            OR
            (changed_by_account_id IS NOT NULL
                AND change_reason IS NOT NULL
                AND char_length(btrim(change_reason)) > 0)
        )
);

CREATE INDEX idx_target_department_day
    ON public.attendance_target (department_id, attendance_day_id);

CREATE INDEX idx_target_membership
    ON public.attendance_target (membership_id);

CREATE INDEX idx_target_member
    ON public.attendance_target (member_id);

CREATE INDEX idx_target_member_day_active
    ON public.attendance_target (member_id, attendance_day_id)
    WHERE is_target;

CREATE INDEX idx_target_changed_by
    ON public.attendance_target (changed_by_account_id)
    WHERE changed_by_account_id IS NOT NULL;


CREATE TABLE public.attendance_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attendance_day_id BIGINT NOT NULL,
    policy_version_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    attendance_band_id BIGINT,
    status TEXT NOT NULL,
    band_sequence_snapshot SMALLINT,
    band_label_snapshot TEXT,
    checked_in_at TIMESTAMPTZ,
    source TEXT NOT NULL,
    note TEXT,
    created_by_account_id BIGINT,
    updated_by_account_id BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_attendance_record_day_member
        UNIQUE (attendance_day_id, member_id),
    CONSTRAINT uq_attendance_record_day_scope
        UNIQUE (id, attendance_day_id),
    CONSTRAINT fk_record_target
        FOREIGN KEY (attendance_day_id, member_id)
        REFERENCES public.attendance_target (attendance_day_id, member_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_record_day_policy
        FOREIGN KEY (attendance_day_id, policy_version_id)
        REFERENCES public.attendance_day (id, policy_version_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_record_band_policy_status
        FOREIGN KEY (
            attendance_band_id,
            policy_version_id,
            status
        )
        REFERENCES public.attendance_band (
            id,
            policy_version_id,
            parent_status
        )
        ON DELETE RESTRICT,
    CONSTRAINT fk_record_created_by
        FOREIGN KEY (created_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_record_updated_by
        FOREIGN KEY (updated_by_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_record_status
        CHECK (status IN ('PRESENT', 'LATE', 'ABSENT')),
    CONSTRAINT ck_record_source
        CHECK (source IN ('NFC', 'AUTO_ABSENCE', 'MANUAL')),
    CONSTRAINT ck_record_source_status
        CHECK (
            (source = 'NFC' AND status IN ('PRESENT', 'LATE'))
            OR (source = 'AUTO_ABSENCE' AND status = 'ABSENT')
            OR source = 'MANUAL'
        ),
    CONSTRAINT ck_record_manual_actor
        CHECK (
            (source = 'MANUAL'
                AND (created_by_account_id IS NOT NULL
                    OR updated_by_account_id IS NOT NULL))
            OR
            (source <> 'MANUAL'
                AND created_by_account_id IS NULL)
        ),
    CONSTRAINT ck_record_band_snapshot
        CHECK (
            (status IN ('PRESENT', 'LATE')
                AND attendance_band_id IS NOT NULL
                AND band_sequence_snapshot IS NOT NULL
                AND band_sequence_snapshot > 0
                AND band_label_snapshot IS NOT NULL
                AND char_length(btrim(band_label_snapshot)) > 0
                AND checked_in_at IS NOT NULL)
            OR
            (status = 'ABSENT'
                AND attendance_band_id IS NULL
                AND band_sequence_snapshot IS NULL
                AND band_label_snapshot IS NULL
                AND checked_in_at IS NULL)
        )
);

CREATE INDEX idx_record_member_day_status
    ON public.attendance_record (member_id, attendance_day_id, status);

CREATE INDEX idx_record_band
    ON public.attendance_record (attendance_band_id)
    WHERE attendance_band_id IS NOT NULL;

CREATE INDEX idx_record_created_by
    ON public.attendance_record (created_by_account_id)
    WHERE created_by_account_id IS NOT NULL;

CREATE INDEX idx_record_updated_by
    ON public.attendance_record (updated_by_account_id)
    WHERE updated_by_account_id IS NOT NULL;


CREATE TABLE public.tag_event_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL,
    department_id BIGINT NOT NULL,
    request_id VARCHAR(64) NOT NULL,
    uid TEXT NOT NULL,
    nfc_card_id BIGINT,
    attendance_day_id BIGINT,
    attendance_record_id BIGINT,
    result_code TEXT NOT NULL,
    http_status INTEGER,
    response_body JSONB,
    failure_type TEXT,
    received_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_tag_event_device_request
        UNIQUE (device_id, request_id),
    CONSTRAINT fk_tag_event_device
        FOREIGN KEY (device_id, department_id)
        REFERENCES public.device (id, department_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_tag_event_card
        FOREIGN KEY (nfc_card_id, uid)
        REFERENCES public.nfc_card (id, uid)
        ON DELETE RESTRICT,
    CONSTRAINT fk_tag_event_day
        FOREIGN KEY (attendance_day_id, department_id)
        REFERENCES public.attendance_day (id, department_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_tag_event_record
        FOREIGN KEY (attendance_record_id, attendance_day_id)
        REFERENCES public.attendance_record (id, attendance_day_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_tag_event_request_id
        CHECK (request_id ~ '^[A-Za-z0-9_-]{1,64}$'),
    CONSTRAINT ck_tag_event_uid
        CHECK (
            uid ~ '^[0-9A-F]+$'
            AND char_length(uid) BETWEEN 8 AND 32
            AND mod(char_length(uid), 2) = 0
        ),
    CONSTRAINT ck_tag_event_result_code
        CHECK (
            result_code IN (
                'PROCESSING',
                'CHECKED_IN',
                'LATE',
                'ALREADY_CHECKED_IN',
                'UNKNOWN_UID',
                'INACTIVE_CARD',
                'NOT_DEPARTMENT_MEMBER',
                'NO_ATTENDANCE_DAY',
                'NOT_ATTENDANCE_TARGET',
                'CHECK_IN_NOT_OPEN',
                'CHECK_IN_CLOSED'
            )
        ),
    CONSTRAINT ck_tag_event_record_day
        CHECK (
            attendance_record_id IS NULL
            OR attendance_day_id IS NOT NULL
        ),
    CONSTRAINT ck_tag_event_response
        CHECK (
            (result_code = 'PROCESSING'
                AND http_status IS NULL
                AND response_body IS NULL)
            OR
            (result_code <> 'PROCESSING'
                AND http_status IS NOT NULL
                AND http_status BETWEEN 100 AND 599
                AND response_body IS NOT NULL)
        )
);

CREATE INDEX idx_tag_event_department_received
    ON public.tag_event_log (department_id, received_at DESC);

CREATE INDEX idx_tag_event_unknown_uid
    ON public.tag_event_log (department_id, received_at DESC)
    WHERE result_code = 'UNKNOWN_UID';

CREATE INDEX idx_tag_event_card_received
    ON public.tag_event_log (nfc_card_id, received_at DESC)
    WHERE nfc_card_id IS NOT NULL;

CREATE INDEX idx_tag_event_day_received
    ON public.tag_event_log (attendance_day_id, received_at DESC)
    WHERE attendance_day_id IS NOT NULL;

CREATE INDEX idx_tag_event_record
    ON public.tag_event_log (attendance_record_id)
    WHERE attendance_record_id IS NOT NULL;


CREATE TABLE public.audit_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_id BIGINT,
    actor_type TEXT NOT NULL,
    actor_account_id BIGINT,
    actor_device_id BIGINT,
    attendance_day_id BIGINT,
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    before_data JSONB,
    after_data JSONB,
    reason TEXT,
    idempotency_key TEXT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_audit_idempotency_key
        UNIQUE (idempotency_key),
    CONSTRAINT fk_audit_department
        FOREIGN KEY (department_id)
        REFERENCES public.department (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_audit_actor_account
        FOREIGN KEY (actor_account_id)
        REFERENCES public.account (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_audit_actor_device_scope
        FOREIGN KEY (actor_device_id, department_id)
        REFERENCES public.device (id, department_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_audit_day
        FOREIGN KEY (attendance_day_id, department_id)
        REFERENCES public.attendance_day (id, department_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_audit_actor
        CHECK (
            (actor_type = 'ACCOUNT'
                AND actor_account_id IS NOT NULL
                AND actor_device_id IS NULL)
            OR
            (actor_type = 'DEVICE'
                AND actor_account_id IS NULL
                AND actor_device_id IS NOT NULL
                AND department_id IS NOT NULL)
            OR
            (actor_type = 'SYSTEM'
                AND actor_account_id IS NULL
                AND actor_device_id IS NULL)
        ),
    CONSTRAINT ck_audit_day_department
        CHECK (
            (attendance_day_id IS NULL AND department_id IS NULL)
            OR
            (attendance_day_id IS NULL AND department_id IS NOT NULL)
            OR
            (attendance_day_id IS NOT NULL AND department_id IS NOT NULL)
        ),
    CONSTRAINT ck_audit_action
        CHECK (char_length(btrim(action)) > 0),
    CONSTRAINT ck_audit_target_type
        CHECK (char_length(btrim(target_type)) > 0),
    CONSTRAINT ck_audit_target_id
        CHECK (char_length(btrim(target_id)) > 0),
    CONSTRAINT ck_audit_reason
        CHECK (reason IS NULL OR char_length(btrim(reason)) > 0),
    CONSTRAINT ck_audit_idempotency_key
        CHECK (
            idempotency_key IS NULL
            OR char_length(btrim(idempotency_key)) > 0
        )
);

CREATE INDEX idx_audit_department_occurred
    ON public.audit_log (department_id, occurred_at DESC)
    WHERE department_id IS NOT NULL;

CREATE INDEX idx_audit_target_occurred
    ON public.audit_log (target_type, target_id, occurred_at DESC);

CREATE INDEX idx_audit_actor_account
    ON public.audit_log (actor_account_id, occurred_at DESC)
    WHERE actor_account_id IS NOT NULL;

CREATE INDEX idx_audit_actor_device
    ON public.audit_log (actor_device_id, occurred_at DESC)
    WHERE actor_device_id IS NOT NULL;

CREATE INDEX idx_audit_day
    ON public.audit_log (attendance_day_id, occurred_at DESC)
    WHERE attendance_day_id IS NOT NULL;


CREATE FUNCTION public.attend_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.attend_set_updated_at() FROM PUBLIC;

CREATE TRIGGER trg_department_updated_at
BEFORE UPDATE ON public.department
FOR EACH ROW
EXECUTE FUNCTION public.attend_set_updated_at();

CREATE TRIGGER trg_account_updated_at
BEFORE UPDATE ON public.account
FOR EACH ROW
EXECUTE FUNCTION public.attend_set_updated_at();

CREATE TRIGGER trg_member_updated_at
BEFORE UPDATE ON public.member
FOR EACH ROW
EXECUTE FUNCTION public.attend_set_updated_at();

CREATE TRIGGER trg_nfc_card_updated_at
BEFORE UPDATE ON public.nfc_card
FOR EACH ROW
EXECUTE FUNCTION public.attend_set_updated_at();

CREATE TRIGGER trg_device_updated_at
BEFORE UPDATE ON public.device
FOR EACH ROW
EXECUTE FUNCTION public.attend_set_updated_at();

CREATE TRIGGER trg_attendance_record_updated_at
BEFORE UPDATE ON public.attendance_record
FOR EACH ROW
EXECUTE FUNCTION public.attend_set_updated_at();


-- The following multi-row and cross-table rules must be validated in the
-- application transaction or implemented later as dedicated PostgreSQL
-- triggers/functions:
--
-- 1. A published policy and its attendance_band rows are immutable.
-- 2. Policy publication requires:
--      - sequence numbers starting at 1 with no gaps;
--      - exactly one PRESENT band at sequence 1;
--      - one or more LATE bands after sequence 1;
--      - check_in_start_time <= the first upper_time;
--      - upper_time values strictly increasing by sequence.
-- 3. attendance_day may reference only a PUBLISHED policy.
-- 4. Normal attendance_target changes are allowed only before check-in starts.
--    The omitted-target recovery exception must atomically insert an active
--    MANUAL target and a MANUAL attendance_record with an authenticated actor
--    and nonblank reason; it is forbidden for CANCELED days.
-- 5. attendance_record may be created only when attendance_target.is_target is
--    true.
-- 6. An attendance_day with attendance_record rows cannot become CANCELED.
-- 7. Card status and active nfc_card_assignment must be updated atomically.
-- 8. Shared rows use this order when applicable: department, device,
--    request-specific tag event (check-in only), affected attendance_day rows
--    in ascending id order, membership/card, target/record, then log. The
--    parent rows must be locked before inserting tag_event_log because its FKs
--    take implicit parent locks. New attendance-day snapshots and roster
--    changes both lock the department row first. This includes check-in,
--    target or policy changes, card or membership changes, cancel, manual
--    correction, and automatic absence finalization. Check-in must re-read and
--    lock card and membership state after obtaining the day lock.
-- 9. An administrator update to attendance status, checked-in time, or band
--     must set attendance_record.source to MANUAL and updated_by_account_id in
--     the same statement. A note-only update preserves the existing source.

COMMIT;
